In [1]:
import numpy as np

In [2]:
X = np.array([[11,15,-9],[2,-6,1],[13,7,-11],[4,18,12]])
X

array([[ 11,  15,  -9],
       [  2,  -6,   1],
       [ 13,   7, -11],
       [  4,  18,  12]])

bir matrisin tam SVD'sini (singular value decomposition) hesaplar. Matris, X olarak tanımlanır ve full_matrices=False parametresi kullanılarak kısaltılmış SVD hesaplanır.

U, Sigma ve Vt olarak adlandırılan üç matris SVD'nin sonuçlarını temsil eder. U, orijinal matrisin satırlarının temel bileşenlerini içeren bir dik matrisdir. Sigma, matrisin singular değerlerinin sıralı bir vektörüdür. Vt, orijinal matrisin sütunlarının temel bileşenlerini içeren bir dik matristir.

diff, X matrisi ile SVD sonucu elde edilen matrislerin çarpımı arasındaki farkı hesaplar. 

In [3]:
U,Sigma,Vt = np.linalg.svd(X,full_matrices=False)
print("U: \n{}".format(U))
print("Sigma: {}".format(Sigma))
print("V transpose: \n{}".format(Vt))

U: 
[[-0.68901721 -0.22432441 -0.32008061]
 [ 0.13596717 -0.11254067  0.82112222]
 [-0.51954264 -0.50533112  0.39152793]
 [-0.48666586  0.82562317  0.26459892]]
Sigma: [29.14354811 20.29457214  5.45746692]
V transpose: 
[[-0.54928016 -0.80799514  0.21315527]
 [-0.29364806  0.4254476   0.85601703]
 [ 0.78234399 -0.40760054  0.47095613]]


bir matrisin SVD işlemini gerçekleştiriyor ve çıktı olarak U, Sigma ve Vt matrislerini veriyor. Daha sonra, U matrisinin bazı özelliklerini kontrol ediyor. U matrisinin sütunları birbirinden bağımsız ve birbirine dik olmalıdır, bu nedenle bu özellikleri kontrol ediyoruz. U matrisinin sütunlarının L2 normunu hesaplayarak sütunların uzunluğunu kontrol ediyoruz. Daha sonra, sütunlar arasındaki nokta çarpımlarını hesaplayarak sütunların birbirine dik olup olmadığını kontrol ediyoruz.

In [4]:
# check
diff = X - np.matmul(U,np.matmul(np.diag(Sigma),Vt))
diff

array([[ 2.30926389e-14, -1.77635684e-15,  5.32907052e-15],
       [ 7.10542736e-15, -6.21724894e-15,  4.77395901e-15],
       [ 4.26325641e-14, -1.24344979e-14,  1.24344979e-14],
       [-5.24025268e-14,  3.55271368e-14, -2.13162821e-14]])

In [5]:
def lengthl2(X):
    # compute l2 length of X
    return np.sqrt(np.sum(np.square(X),axis=0))

In [6]:
# check lengths
print("L2 Length U0: {}".format(lengthl2(U[:,0])))
print("L2 length U1: {}".format(lengthl2(U[:,1])))
print("L2 length U2: {}".format(lengthl2(U[:,2])))

L2 Length U0: 0.9999999999999998
L2 length U1: 0.9999999999999996
L2 length U2: 0.9999999999999999


In [7]:
# check dot products:
print("U0.T dot U1: {}".format(np.dot(U[:,0].T,U[:,1])))
print("U0.T dot U2: {}".format(np.dot(U[:,0].T,U[:,2])))
print("U1.T dot U2: {}".format(np.dot(U[:,1].T,U[:,2])))

U0.T dot U1: 5.551115123125783e-17
U0.T dot U2: 3.122502256758253e-17
U1.T dot U2: 0.0


In [8]:
V = Vt.T
# check lengths
print("L2 Length V0: {}".format(lengthl2(V[:,0])))
print("L2 length V1: {}".format(lengthl2(V[:,1])))
print("L2 length V2: {}".format(lengthl2(V[:,2])))

L2 Length V0: 0.9999999999999999
L2 length V1: 0.9999999999999999
L2 length V2: 1.0


In [9]:
# check dot products:
print("V0.T dot V1: {}".format(np.dot(V[:,0].T,V[:,1])))
print("V0.T dot V2: {}".format(np.dot(V[:,0].T,V[:,2])))
print("V1.T dot V2: {}".format(np.dot(V[:,1].T,V[:,2])))

V0.T dot V1: -1.0293120698731393e-16
V0.T dot V2: 2.437230818347938e-16
V1.T dot V2: 4.405452741293694e-17
