In [1]:
import numpy as np

Aşağıdaki kodda X adlı bir numpy array oluşturulmuştur. Bu X array'ı 3 satır ve 6 sütundan oluşmaktadır.

In [2]:
X = np.array([[1,2,3,-1,-3,-4],[4,5,7,-6,-5,-7],[7,8,9,2,4,6]])
X

array([[ 1,  2,  3, -1, -3, -4],
       [ 4,  5,  7, -6, -5, -7],
       [ 7,  8,  9,  2,  4,  6]])

Aşağıdaki kodda a adlı bir numpy array oluşturulmuştur. 1 satır ve 6 sütundan oluşmaktadır.

In [3]:
a = np.array([0,1,1,0,1,1])
a

array([0, 1, 1, 0, 1, 1])

Exercise (a)

np.where() NumPy kütüphanesindeki bir fonksiyondur ve belirli bir koşulu sağlayan öğelerin konumlarını (indekslerini) döndürür.

Aşağıdaki kodda a numpy array'ındeki elemanlardan sadece 0 olan elemanların indekslerini döndürmek için kullanılır. inx0 yine bir numpy array döndürür ve a dizisinde birinci ve dördüncü itemların 0 olduğunu bize söyler. (sıfırıncı ve üçüncü itemlar)

In [4]:
idx0 = np.where(a==0)[0]
idx0

array([0, 3])

Exercise (b)

X array'indeki tüm satırları ve a array'indeki sadece 0 olan elemanların indekslerine karşılık gelen sütunları seçmek için X[:, idx0] ifadesi kullanılır. Bu kod, X dizisinin tüm satırlarını ve idx0 array'ındeki sütunları içeren yeni bir numpy dizisi olan Y'yi oluşturur.

In [5]:
Y = X[:,idx0]
Y

array([[ 1, -1],
       [ 4, -6],
       [ 7,  2]])

Exercise (c)

mean() fonksiyonu ortalama hesaplamak için kullanılır.
axis=1 her saturun ortalamasının alınacağını belirtir.
keepdims=True fonksiyonun sonucunun 2D bir numpy array'ıne dönüştürülmesini sağlar.
Kısacası bu kodda Y array'inin ortalaması mean0 numpy dizisine aktarılıyor.

In [6]:
mean0 = np.mean(Y,axis=1,keepdims=True)
mean0

array([[ 0. ],
       [-1. ],
       [ 4.5]])

Exercise (d)

a arrayinde item'ı 1 olanları idx1 numpy dizisine dönüştürülmiştür.

In [7]:
idx1 = np.where(a==1)[0]
idx1

array([1, 2, 4, 5])

Exercise (e)

a vektöründe 1 olan elemanların indekslerine karşılık gelen sütunları seçmek için X[:, idx1] işlemi kullanılır. Bu, X matrisindeki tüm satırları ve idx1 listesindeki sütunları içeren bir alt matrisi oluşturur.



In [8]:
Z = X[:,idx1]
Z

array([[ 2,  3, -3, -4],
       [ 5,  7, -5, -7],
       [ 8,  9,  4,  6]])

Exercise (f)

Z arrayindeki her satırın ortalaması alınır ve keepdims=True parametresi, döndürülen matrisin boyutlarını orijinal matrisle aynı tutar. Yapılan bu işlem mean1 numpy arrayine atılır.

In [9]:
mean1 = np.mean(Z,axis=1,keepdims=True)
mean1

array([[-0.5 ],
       [ 0.  ],
       [ 6.75]])