Aşağıda numpy array oluşturma ve bu arraylerle toplama çarpma gibi 4 işlem yapabilmek 
için bazı kodlar yazılmıştır.

In [1]:
import numpy as np

exercise(a):

burada, X adında numpy dizisi oluşturulmuştur. 2 satır ve 3 sütündan oluşmaktadır. Aynı şekilde 
X numpy array'ı oluşturulmuştur ve 1 satırdan oluşmaktadır. Z numpy array'ı ise 3 satır 
2 sütündan oluşmaktadır.

In [2]:
X = np.array([[1, 2, 4], [-2, -5, -8]])
X

array([[ 1,  2,  4],
       [-2, -5, -8]])

In [3]:
Y = np.array([[1, 2, 3]])
Y

array([[1, 2, 3]])

In [4]:
Z = np.array([[1, 2], [3, 4], [5,7]])
Z

array([[1, 2],
       [3, 4],
       [5, 7]])

Exercise (b)

**np.concatenate()** fonksiyonu 2 veya daha fazla numpy dizisini birleştirmek için 
kullanılır. Birleştirme işlemi, iki dizinin birleştirileceği eksen (satır veya sütun) 
belirtilerek yapılır. axis=0 ise iki dizi satır bazında birleştirilir eğer axis=1 ise 
iki dizi sütun bazında birleştirilir. Bu yüzden iki dizinin aynı 
satır sayısına sahip olması gerekir.

aşağıdaki kodda, X ve Y arrayleri kullanılarak XYrow adlı bir numpy dizisi oluşturulmuştur. 
ve yeni oluşturulan XYrow dizisi 3 satır ve 3 sütundan oluşmaktadır.


In [5]:
XYrow = np.concatenate((X, Y), axis=0)
XYrow

array([[ 1,  2,  4],
       [-2, -5, -8],
       [ 1,  2,  3]])

Exercise (c)

**np.reshape()** fonksiyonu, numpy dizilerinin boyutunu yeniden şekillendirmek 
için kullanılır. Bu fonksiyon, orijinal dizi elemanlarının birbirleriyle aynı 
sırayla yeniden düzenlenerek yeni bir dizi oluşturur. Bu işlem sırasında, 
orijinal dizi eleman sayısı ve yeni şekle uyumlu bir eleman sayısı olması gerekmektedir. 
Bu fonksiyon özellikle makine öğrenmesi gibi veri bilimi uygulamalarında, verilerin 
işlenmesinde sıkça kullanılır.

aşağıdaki kodda, np.reshape() fonksiyonu kullanılarak, Z numpy array'ı yeniden 
şekillendirilmiştir. İlk parametre olarak Z verilmiştir. İkinci parametre (2,3) 
tuple'ı belirtilerek 2 satır 3 sütundan oluşan bi array'e dönüştürülmüştür. 
Ve yapılan bu işlem Zreshape olarak adlandırılmuştır.

In [6]:
Zreshape = np.reshape(Z,(2,3))
Zreshape

array([[1, 2, 3],
       [4, 5, 7]])

Exercise (d)

Yukarıda elde edilen X, Y ve Zreshape numpy arrayleri toplanarak yeni bir array 
oluşturulmuştur (Answer). Y numpy arrayinin 3 katı alınmıştır ve X, Zreshape ile 
toplanmıştır.

In [7]:
Answer = X + 3*Y + Zreshape
Answer

array([[ 5, 10, 16],
       [ 5,  6,  8]])

Exercise (e)

Aşağıdaki kodda, X ve Y numpy arrayleri çarpılmıştır ve yeni oluşturulan Answer 
numpy array'ı 2 satır ve 3 sütundan oluşmaktadır.

In [8]:
Answer = X*Y
Answer

array([[  1,   4,  12],
       [ -2, -10, -24]])