In [1]:
import numpy as np

W numpy dizisi oluşturulmuştur. 2 satır 2 sütundan oluşmaktadır.

In [2]:
W = np.array([[1,2],[3,4]])
W

array([[1, 2],
       [3, 4]])

X numpy arrayi oluşturulmuştur. 2 satır 3 sütundan oluşmaktadır.

In [3]:
X = np.array([[1,2,4],[-2,-5,-8]])
X

array([[ 1,  2,  4],
       [-2, -5, -8]])

Y numpy arrayi oluşturulmuştur. 1 satır 3 sütundan oluşmuştur.

In [4]:
Y = np.array([[1, 2, 3]])
Y

array([[1, 2, 3]])

Z dizisi oluşturulmuştur. 3 satır 2 sütundan oluşmaktadır.

In [5]:
Z = np.array([[1, 2], [3, 4], [5,7]])
Z

array([[1, 2],
       [3, 4],
       [5, 7]])

(a)

X ve Y dizisi toplanarak result adlı bir dizi oluşturulmuştur.

In [6]:
result = X + Y
result

array([[ 2,  4,  7],
       [-1, -3, -5]])

(b)

matris çarpımının kuralı gereği m x n boyutlu bir matris ve n x y botuylu bir matris çarpılabilmektedir. Bu şartı sağladığından W ve X matrisleri çarpılabilir.


**np.matmul** fonksiyonu, W matrisi ile X matrisini çarpmaktadır.

In [7]:
result = np.matmul(W,X)
result

array([[ -3,  -8, -12],
       [ -5, -14, -20]])

(c)

Y matrisinin transpozu alınmıştır ve Z matrisi ile toplanmıştır sonuç ise result numpy arrayine atanmıştır.

In [8]:
result = Z + Y.T
result

array([[ 2,  3],
       [ 5,  6],
       [ 8, 10]])

(d)

**np.linalg.inv** fonksiyonu kullanılarak W matrisinin tersi alınmıştır. X ve Y matrislerinin çarpımı alınmıştır. 
Son olarak bir kez daha matris çarpımı yaparak sonuç matrisi result elde edilmiştir.

In [9]:
result = np.matmul(np.matmul(X,Z),np.linalg.inv(W))
result

array([[  3.,   8.],
       [ -6., -17.]])

(e)

Z matrisinin transpozu alınarak X matrisi ile toplanmıştır.

In [10]:
result = X + Z.T
result

array([[ 2,  5,  9],
       [ 0, -1, -1]])

(f)

Z matrisi ile X matrisi matris çarpımı hesaplanmıştır.

In [11]:
result = np.matmul(Z,X)
result

array([[ -3,  -8, -12],
       [ -5, -14, -20],
       [ -9, -25, -36]])

(g)

X.T ve Z.T matrisleri hesaplandıktan sonra (T= transpozu alındıktan sonra) bu iki matrisin matris çarpımı hesaplanmıştır.

In [12]:
result = np.matmul(X.T,Z.T)
result

array([[ -3,  -5,  -9],
       [ -8, -14, -25],
       [-12, -20, -36]])