In [1]:
import pandas as pd
import numpy as np

In [3]:
df1 = pd.read_csv('mydf1.csv')
df1.head()

label  feature 1  feature 2
0  0.123   0.715279  -1.545400
1  1.230   0.500000  -0.720086
2 -1.450   0.500000   0.004291
3  0.510   0.433026   1.203037

(a)

aşağıdaki kod label sütunundaki değerleri alıp Y değişkenine kaydeder ve Y'deki her bir itemın karesini hesaplar.

In [4]:
Y = df1['label'].values
Y = np.square(Y)
Y

array([0.015129, 1.5129  , 2.1025  , 0.2601  ])

(b)

"feature 1" ve "feature 2" sütunlarını X numpy arrayine kaydeder ve X'i döndürür.
Daha sonra, "X" dizisinin ilk sütunundaki her bir elemanın karekökünü hesaplar ve bunu ilk sütuna yazar. Ayrıca, "X" dizisinin ikinci sütunundaki her bir elemanın üstel fonksiyonunu hesaplar ve bunu ikinci sütuna yazar.

In [5]:
X = df1[["feature 1","feature 2"]].values
X

array([[ 0.71527897, -1.54540029],
       [ 0.5       , -0.72008556],
       [ 0.5       ,  0.00429143],
       [ 0.43302619,  1.20303737]])

In [6]:
X[:,0] = np.sqrt(X[:,0])
X[:,1] = np.exp(X[:,1])
X

array([[0.84574167, 0.2132265 ],
       [0.70710678, 0.48671061],
       [0.70710678, 1.00430065],
       [0.65804726, 3.33021669]])