In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from wordcloud import WordCloud

list message listesi tanımlanmıştır. 

In [2]:
#dataset
list_message = ["A bird in the hand is worth two in the bush", "The early bird gets the worm", "Time is money",
               "Honesty is the best policy"]


Aşağıdaki kod metin belgeleri üzerinde kelime sayımı yapmaktadır ve sonucu matriste göstermektedir.

**CountVectorizer** metin verilerinden özellik matrisleri oluşturmak için kullanılan bir sınıftır. Verilen metin belgelerinden her bir kelimenin frekansını sayar ve her kelimeyi bir özellik olarak ele alarak bir özellik matrisi oluşturur. Bu özellik matrisi, makine öğrenimi algoritmalarında kullanılabilecek sayısal bir formattadır. Özellikle, doğrusal olmayan modellerle kullanılmak üzere tasarlanmıştır.

**max_features** 100 olarak ayarlanmıştır bu parametre en fazla kaç kelimenin alınacağını belirtmektedir.

**fit_transform()** yöntemi kullanılarak, verilen belgeler üzerinde kelime sayımları yapılmaktadır.

**toarray()** fonksiyonu ile oluşturulan matris numpy array'ine 
dönüştürülür.

**get_feature_names_out()** fonksiyonu özelliklerin sıralı bir listesini döndürür.

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

# create instance of count vectorizer
vectorizer = CountVectorizer(max_features=100)
# perform word counts
Xfit = vectorizer.fit_transform(list_message)
# generate feature matrix (transform so sample axis is in column direction)
X = Xfit.toarray().T
print("X: \n{}".format(X))
# list words in vocabulary (turn into numpy array)
words = np.array(vectorizer.get_feature_names_out())
print("Words: {}".format(words))


X: 
[[0 0 0 1]
 [1 1 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [2 0 0 0]
 [1 0 1 1]
 [0 0 1 0]
 [0 0 0 1]
 [2 2 0 1]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]]
Words: ['best' 'bird' 'bush' 'early' 'gets' 'hand' 'honesty' 'in' 'is' 'money'
 'policy' 'the' 'time' 'two' 'worm' 'worth']


Aşağıdaki kodda Tf-Idf özellik matrisini oluşturur ve oluşturulan matrisi ve kelime dağarcığını ekrana yazdırır.

**TfidfVectorizer**, "Term Frequency-Inverse Document Frequency" (TF-IDF) yöntemi kullanarak belgelerdeki kelimelerin önem derecelerini hesaplamak için kullanılan bir vektörleştirici sınıfıdır. Bu sınıf, bir metin belgesindeki her kelimenin bir sayısal vektörle temsil edildiği bir dizi sayı döndürür. Bu sayılar, kelimenin belge içindeki görülme sıklığına ve tüm belgelerdeki görülme sıklığına bağlı olarak hesaplanır. TF-IDF, bir kelimenin önemini belirlemek için kelimenin sıklığına odaklanırken, aynı zamanda kelimenin nadir olup olmadığını da dikkate alır. Bu nedenle, bir belge içindeki sık kullanılan kelimelerin önemi düşükken, nadir kullanılan kelimelerin önemi yüksektir.

**Xfit_tfidf**'in T (transpozu alınarak) öznitelik matrisi oluşturulur.

**get_feature_names_out()** fonksiyonu özelliklerin sıralı bir listesini döndürür.

Tüm bu işlemlerin sonunda, **Tf-Idf** matrisi (X_tfidf) ve kelime dağarcığı (words_tfidf) yazdırılır.

In [4]:
# Create instance of vectorizer
vectorizer_tfidf = TfidfVectorizer()
# Perform word counts
Xfit_tfidf = vectorizer_tfidf.fit_transform(list_message)
# Generate feature matrix (transpose so sample axis is in column direction)
X_tfidf = Xfit_tfidf.toarray().T
print("X_tfidf: \n{}".format(X_tfidf))
# list words in vocabulary (turn into numpy array)
words_tfidf = np.array(vectorizer_tfidf.get_feature_names_out())
print("Words: {}".format(words_tfidf))

X_tfidf: 
[[0.         0.         0.         0.51199172]
 [0.24149156 0.34405055 0.         0.        ]
 [0.30630142 0.         0.         0.        ]
 [0.         0.43638449 0.         0.        ]
 [0.         0.43638449 0.         0.        ]
 [0.30630142 0.         0.         0.        ]
 [0.         0.         0.         0.51199172]
 [0.61260284 0.         0.         0.        ]
 [0.19550823 0.         0.41137791 0.32679768]
 [0.         0.         0.64450299 0.        ]
 [0.         0.         0.         0.51199172]
 [0.39101646 0.55707714 0.         0.32679768]
 [0.         0.         0.64450299 0.        ]
 [0.30630142 0.         0.         0.        ]
 [0.         0.43638449 0.         0.        ]
 [0.30630142 0.         0.         0.        ]]
Words: ['best' 'bird' 'bush' 'early' 'gets' 'hand' 'honesty' 'in' 'is' 'money'
 'policy' 'the' 'time' 'two' 'worm' 'worth']


(a)

df = (X>0), bir kelimenin belirli bir belgede bulunup bulunmadığını belirlemek için kullanılır. Eğer X matrisindeki 
tüm elemanlar 0'dan büyük ise **True** döndürülür, diğer durumlarda **False** döndürülür.

In [5]:
# Create matrix of True False if word i appears in document j
df = (X>0)
df

array([[False, False, False,  True],
       [ True,  True, False, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [ True, False, False, False],
       [False, False, False,  True],
       [ True, False, False, False],
       [ True, False,  True,  True],
       [False, False,  True, False],
       [False, False, False,  True],
       [ True,  True, False,  True],
       [False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [ True, False, False, False]])

Aşağıdaki kodda, df numpy array'indeki tüm itemlar toplanır.

In [6]:
### sum in column direction to get document frequency vector
df = np.sum(df,axis=1,keepdims=True)
df

array([[1],
       [2],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [3],
       [1],
       [1],
       [3],
       [1],
       [1],
       [1],
       [1]])

(b)

Bir kelimenin tüm belgelerde kaç kez yazıldığını bulmak için aşağıdaki kod yazılmıştır.

list_message listesinin uzunluğu bulunur.

**n** = belge sayısıdır.
**df_i** = kelimenin görüldüğü belge sayısıdır.

**log((1+ndoc)/(1+df))+1** hesaplandıktan sonra *idf* değişkenine atanır.

In [7]:
ndoc = len(list_message)
idf = np.log((1+ndoc)/(1+df))+1
idf

array([[1.91629073],
       [1.51082562],
       [1.91629073],
       [1.91629073],
       [1.91629073],
       [1.91629073],
       [1.91629073],
       [1.91629073],
       [1.22314355],
       [1.91629073],
       [1.91629073],
       [1.22314355],
       [1.91629073],
       [1.91629073],
       [1.91629073],
       [1.91629073]])

(c)

X matrisi ile idf matrisi çarpılır.

In [8]:
tfidf = X*idf
tfidf

array([[0.        , 0.        , 0.        , 1.91629073],
       [1.51082562, 1.51082562, 0.        , 0.        ],
       [1.91629073, 0.        , 0.        , 0.        ],
       [0.        , 1.91629073, 0.        , 0.        ],
       [0.        , 1.91629073, 0.        , 0.        ],
       [1.91629073, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.91629073],
       [3.83258146, 0.        , 0.        , 0.        ],
       [1.22314355, 0.        , 1.22314355, 1.22314355],
       [0.        , 0.        , 1.91629073, 0.        ],
       [0.        , 0.        , 0.        , 1.91629073],
       [2.4462871 , 2.4462871 , 0.        , 1.22314355],
       [0.        , 0.        , 1.91629073, 0.        ],
       [1.91629073, 0.        , 0.        , 0.        ],
       [0.        , 1.91629073, 0.        , 0.        ],
       [1.91629073, 0.        , 0.        , 0.        ]])

(d)

Bu kodda ise axis=0 olduğundan sütun bazında işlemler yapılır.
tfidf matrisinin karesi alınır.keepdims=True olduğu için sonucun boyutu korunacaktır. Bu işlemlerin toplamı alınır. Ve en sonunda bu toplamın karekökü hesaplanmıştır.

In [9]:
lencoltfidf = np.sqrt(np.sum(np.square(tfidf),axis=0,keepdims=True))
lencoltfidf

array([[6.25622539, 4.39128969, 2.97328446, 3.74281589]])

(e)

tfidf matrisi, lencoltfidf matrisine bölünerek tfidf matrisi adı verilmiştir.


In [10]:
tfidf = tfidf/lencoltfidf
tfidf

array([[0.        , 0.        , 0.        , 0.51199172],
       [0.24149156, 0.34405055, 0.        , 0.        ],
       [0.30630142, 0.        , 0.        , 0.        ],
       [0.        , 0.43638449, 0.        , 0.        ],
       [0.        , 0.43638449, 0.        , 0.        ],
       [0.30630142, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.51199172],
       [0.61260284, 0.        , 0.        , 0.        ],
       [0.19550823, 0.        , 0.41137791, 0.32679768],
       [0.        , 0.        , 0.64450299, 0.        ],
       [0.        , 0.        , 0.        , 0.51199172],
       [0.39101646, 0.55707714, 0.        , 0.32679768],
       [0.        , 0.        , 0.64450299, 0.        ],
       [0.30630142, 0.        , 0.        , 0.        ],
       [0.        , 0.43638449, 0.        , 0.        ],
       [0.30630142, 0.        , 0.        , 0.        ]])

In [11]:
X_tfidf

array([[0.        , 0.        , 0.        , 0.51199172],
       [0.24149156, 0.34405055, 0.        , 0.        ],
       [0.30630142, 0.        , 0.        , 0.        ],
       [0.        , 0.43638449, 0.        , 0.        ],
       [0.        , 0.43638449, 0.        , 0.        ],
       [0.30630142, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.51199172],
       [0.61260284, 0.        , 0.        , 0.        ],
       [0.19550823, 0.        , 0.41137791, 0.32679768],
       [0.        , 0.        , 0.64450299, 0.        ],
       [0.        , 0.        , 0.        , 0.51199172],
       [0.39101646, 0.55707714, 0.        , 0.32679768],
       [0.        , 0.        , 0.64450299, 0.        ],
       [0.30630142, 0.        , 0.        , 0.        ],
       [0.        , 0.43638449, 0.        , 0.        ],
       [0.30630142, 0.        , 0.        , 0.        ]])