In [1]:
import numpy as np

3 x 5 boyutl matris oluşturulur.

In [2]:
X = np.array([[1,-2,3,-4,5],[6,7,-10,11,3],[8,9,12,-13,2]])
nsample = X.shape[1]
X

array([[  1,  -2,   3,  -4,   5],
       [  6,   7, -10,  11,   3],
       [  8,   9,  12, -13,   2]])

X matrisinin her satırındaki elemanların ortalaması hesaplanır.

In [3]:
mean = np.mean(X,axis=1,keepdims=True)
mean

array([[0.6],
       [3.4],
       [3.6]])

X matrisinden ortalama matrisi çıkartılır.
Daha sonra kovaryansı hesaplanır.

In [4]:
Xmm = X - mean
cov = np.matmul(Xmm,Xmm.T)/(nsample-1)
cov

array([[ 13.3, -19.3,  19.3],
       [-19.3,  64.3, -51.8],
       [ 19.3, -51.8,  99.3]])