In [4]:
import numpy as np
import time

Veri setleri oluşturulmuştur.

In [5]:
X = np.array([[1,5,9],[2,6,10],[3,7,11],[4,8,12]])
Y = np.array([[11,15,-9],[2,-6,1],[13,7,-11],[4,18,12]])
print("X: \n{}".format(X))
print("Y: \n{}".format(Y))

X: 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Y: 
[[ 11  15  -9]
 [  2  -6   1]
 [ 13   7 -11]
 [  4  18  12]]


(a) 
Her veri kümesinin ortalamasını hesaplanmıştır
X veri kümesinin ortalaması alınmıştır

In [6]:
# mean of dataset X
Xmean = np.mean(X,axis=1,keepdims=True)
print("Xmean: \n{}".format(Xmean))

Xmean: 
[[5.]
 [6.]
 [7.]
 [8.]]


Y veri kümesinin ortalaması alınmıştır.

In [7]:
# mean of dataset Y
Ymean = np.mean(Y,axis=1,keepdims=True)
print("Ymean: \n{}".format(Ymean))

Ymean: 
[[ 5.66666667]
 [-1.        ]
 [ 3.        ]
 [11.33333333]]


Küme ortalamaları arasındaki mesafe hesaplanmıştır.

In [8]:
distance = np.sqrt(np.sum(np.square(Xmean-Ymean),axis=0,keepdims=True))
print("distance: {}".format(distance))

distance: [[8.74960317]]
